allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  esbuild: true
  maplibre-gl: false
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@nuxtjs/mcp-toolkit@0.18.0'
