export const AI_JOB_ANALYZER = Symbol('AI_JOB_ANALYZER');
export const AI_TRENDS_ANALYZER = Symbol('AI_TRENDS_ANALYZER');
export const AI_JOB_SUMMARIZER = Symbol('AI_JOB_SUMMARIZER');
export const AI_CV_ANALYZER = Symbol('AI_CV_ANALYZER');
export const AI_WORK_MODE_CLASSIFIER = Symbol('AI_WORK_MODE_CLASSIFIER');
export const AI_RELEVANCE_CLASSIFIER = Symbol('AI_RELEVANCE_CLASSIFIER');
export const AI_RESUME_TAILOR = Symbol('AI_RESUME_TAILOR');
export const AI_PROFILE_TRANSLATOR = Symbol('AI_PROFILE_TRANSLATOR');
